export const uiCopy = {
  metadata: {
    title: "记忆库",
    description: "一个克制、清晰、可继续扩展的个人知识库最小版本。",
  },
  common: {
    close: "关闭",
    cancel: "取消",
    delete: "删除",
    save: "保存",
    edit: "编辑",
    finish: "完成",
  },
  library: {
    filters: {
      allTopics: "全部主题",
      defaultTopic: "快速记录",
      untitledNote: "未命名知识",
    },
    sidebar: {
      badge: "个人知识库",
      title: "记忆库",
      description: "一个轻量的知识空间，用来整理笔记、资料和 AI 生成草稿。",
      workspaceButton: "工作台",
      statsTitle: (count: number) => `知识库中共有 ${count} 条知识`,
      statsDescription: "按主题浏览、搜索和整理，让每条知识都更容易被再次调用。",
      topics: "主题",
    },
    topBar: {
      eyebrow: "知识库",
      title: "把知识整理成可复用的卡片",
      resultCount: (count: number) => `当前显示 ${count} 条知识，可随时检索、查看和继续生成。`,
      searchPlaceholder: "搜索标题、摘要、内容或标签",
      createButton: "新增知识",
    },
    emptyState: {
      title: "当前筛选下没有知识",
      description: "可以换个关键词、切换主题，或者直接新增一条知识。",
    },
    modal: {
      title: "新增知识",
      description: "添加一条本地知识记录，保存后会先经 AI 整理，再写入当前本地状态。",
      titleLabel: "标题",
      titlePlaceholder: "未命名知识",
      contentLabel: "内容",
      contentPlaceholder: "粘贴或输入这条知识的原始内容...",
      topicLabel: "主题",
      topicHelp: "主题是知识的主分类，会影响侧边栏浏览和默认标签。",
      tagsLabel: "标签",
      tagsPlaceholder: "输入标签后按回车或逗号添加",
      tagsHint: "如果不填写标签，保存时会自动使用当前主题作为默认标签。",
      currentTopicHint: "当前会默认使用这个主题，你也可以在这里切换。",
      addTag: "添加标签",
      removeTag: "移除标签",
      save: "保存",
    },
    drawer: {
      eyebrow: "知识详情",
      createdAt: "创建时间",
      topic: "主题",
      tags: "标签",
      originalContent: "原始内容",
      askButton: "基于这条提问",
      deleteButton: "删除知识",
      deleteConfirm: (title: string) => `确认删除“${title}”吗？此操作只会影响当前本地演示数据。`,
    },
  },
  workspace: {
    header: {
      eyebrow: "工作台",
      title: "围绕已选资料提问、整理与生成",
      description: "三栏最小版本工作台，左侧支持管理知识库资料、本地资料和网页链接。",
      focusedSourcePrefix: "当前焦点资料：",
      webFallbackToggle: "允许联网补充",
    },
    sources: {
      back: "返回知识库",
      eyebrow: "参考资料",
      title: "已选资料",
      description: (count: number) => `当前共选择 ${count} 条资料，左侧仅展示概览，便于快速管理与切换。`,
      addButton: "添加资料",
      addDialogTitle: "添加资料",
      addDialogDescription: "从知识库、本地资料或网页链接中补充工作台参考来源。",
      knowledgeTab: "知识库",
      fileTab: "本地资料",
      linkTab: "网页链接",
      allTopics: "全部主题",
      allTags: "全部标签",
      searchPlaceholder: "搜索标题",
      pickerTitle: "选择知识库资料",
      pickerDescription: "从现有知识库中挑选一条或多条资料加入工作台。",
      pickerSave: "加入工作台",
      pickerEmpty: "当前筛选下没有可添加的资料。",
      pickerSelected: (count: number) => `已选择 ${count} 条资料`,
      topicFilterLabel: "按主题筛选",
      tagFilterLabel: "按标签筛选",
      searchLabel: "搜索标题",
      remove: "删除",
      emptyTitle: "暂无资料",
      emptyDescription: "先从知识库、本地资料或网页链接中添加参考资料。",
      knowledgeSectionTitle: "知识库资料",
      knowledgeSectionDescription: "只展示标题、主题、标签和摘要概览，方便批量浏览。",
      knowledgeBadge: "知识库",
      knowledgeEmpty: "暂无知识库资料",
      alreadyAdded: "已加入",
      fileSectionTitle: "本地资料",
      fileSectionDescription: "仅记录文件基础信息，不上传也不解析内容。",
      fileBadge: "本地",
      fileDialogDescription: "当前版本不会上传文件，只保存名称、类型、大小和添加时间。",
      fileDialogAction: "选择本地文件",
      fileDialogHint: "可一次选择多个文件，加入后会立即出现在左侧资料列表中。",
      fileDialogListTitle: "已添加的本地资料",
      fileEmpty: "暂无本地资料",
      fileUploadedAt: "添加时间",
      linkSectionTitle: "网页链接",
      linkSectionDescription: "添加后会自动抓取网页正文，只在左侧展示标题、摘要和状态概览。",
      linkBadge: "网页",
      linkDialogTabDescription: "保存后会在服务端抓取网页内容，并自动生成摘要与标签。",
      linkAddButton: "添加链接",
      linkEditButton: "编辑",
      linkEmpty: "暂无网页链接",
      linkDialogCreateTitle: "添加链接",
      linkDialogEditTitle: "编辑链接",
      linkTitleLabel: "标题（可选）",
      linkTitlePlaceholder: "例如：产品官网 / 文章标题",
      linkUrlLabel: "链接",
      linkUrlPlaceholder: "请输入网页链接",
      linkInvalidUrl: "请输入有效链接",
      linkUntitled: "未命名链接",
      linkDomainLabel: "域名",
      linkParsingHint: "正在解析网页...",
      linkResolveError: "网页解析失败，请检查链接后重试。",
      linkStatusLoading: "解析中",
      linkStatusReady: "已解析",
      linkStatusError: "解析失败",
      linkSaveCreate: "添加链接",
      linkSaveEdit: "保存链接",
      sourceCount: (count: number) => `${count} 条`,
    },
    chat: {
      eyebrow: "对话",
      title: "基于已选资料提问",
      description: "回答只基于左侧已选资料，资料不足时会明确说明。",
      citationsLabel: "引用来源",
      inputPlaceholder: "输入你的问题，基于这些资料继续展开...",
      hint: "回答仅使用当前已选资料，不做外部抓取或额外补充。",
      hintWithWebFallback: "优先使用当前资料；资料不足时会按需联网补充。",
      emptyHint: "尚未选择资料，先在左侧添加参考资料。",
      emptyHintWithWebFallback: "可直接提问；如果本地资料为空，将按你的问题联网补充。",
      send: "发送",
    },
    generation: {
      eyebrow: "生成",
      title: "结果面板",
      description: "在轻量总结和 PRD 提纲之间切换查看，并同步展示当前引用来源。",
      sourcesLabel: "引用来源",
      sourcesEmpty: "尚未选择资料",
      summaryTab: "总结",
      prdOutlineTab: "PRD 提纲",
      summaryHintWithWebFallback: "点击上方按钮，优先基于当前资料生成；资料不足时会按需联网补充。",
      prdHintWithWebFallback: "点击上方按钮，优先基于当前资料生成；资料不足时会按需联网补充。",
      emptyHintWithWebFallback:
        "尚未选择资料。生成时会先尝试判断是否能联网补充，但更适合先添加至少一条主题资料。",
    },
  },
} as const;
